/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace NightFairHygiene {
  export type VendorStruct = {
    id: BigNumberish;
    name: string;
    location: string;
    exists: boolean;
    ratingCount: BigNumberish;
  };

  export type VendorStructOutput = [
    id: bigint,
    name: string,
    location: string,
    exists: boolean,
    ratingCount: bigint
  ] & {
    id: bigint;
    name: string;
    location: string;
    exists: boolean;
    ratingCount: bigint;
  };

  export type RatingStruct = {
    rater: AddressLike;
    timestamp: BigNumberish;
    evidenceHash: BytesLike;
  };

  export type RatingStructOutput = [
    rater: string,
    timestamp: bigint,
    evidenceHash: string
  ] & { rater: string; timestamp: bigint; evidenceHash: string };
}

export interface NightFairHygieneInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "COOLDOWN_PERIOD"
      | "addAuthority"
      | "allowAuthorityAccess"
      | "confidentialProtocolId"
      | "getAllVendorIds"
      | "getVendorAggregatedScores"
      | "getVendorEvidenceHashes"
      | "getVendorInfo"
      | "getVendorRatingHistory"
      | "isAuthorizedAuthority"
      | "lastRatingTime"
      | "owner"
      | "registerVendor"
      | "removeAuthority"
      | "submitRating"
      | "vendorAggregatedCleanliness"
      | "vendorAggregatedGloveWearing"
      | "vendorAggregatedWasteManagement"
      | "vendorCount"
      | "vendorIds"
      | "vendors"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AuthorityAdded"
      | "AuthorityRemoved"
      | "RatingSubmitted"
      | "VendorRegistered"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "COOLDOWN_PERIOD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addAuthority",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "allowAuthorityAccess",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "confidentialProtocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAllVendorIds",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getVendorAggregatedScores",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getVendorEvidenceHashes",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getVendorInfo",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getVendorRatingHistory",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isAuthorizedAuthority",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lastRatingTime",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "registerVendor",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "removeAuthority",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "submitRating",
    values: [
      BigNumberish,
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "vendorAggregatedCleanliness",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "vendorAggregatedGloveWearing",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "vendorAggregatedWasteManagement",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "vendorCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "vendorIds",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "vendors",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "COOLDOWN_PERIOD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addAuthority",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "allowAuthorityAccess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confidentialProtocolId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllVendorIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getVendorAggregatedScores",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getVendorEvidenceHashes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getVendorInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getVendorRatingHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isAuthorizedAuthority",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastRatingTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerVendor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeAuthority",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitRating",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "vendorAggregatedCleanliness",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "vendorAggregatedGloveWearing",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "vendorAggregatedWasteManagement",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "vendorCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "vendorIds", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "vendors", data: BytesLike): Result;
}

export namespace AuthorityAddedEvent {
  export type InputTuple = [authority: AddressLike];
  export type OutputTuple = [authority: string];
  export interface OutputObject {
    authority: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AuthorityRemovedEvent {
  export type InputTuple = [authority: AddressLike];
  export type OutputTuple = [authority: string];
  export interface OutputObject {
    authority: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RatingSubmittedEvent {
  export type InputTuple = [
    vendorId: BigNumberish,
    rater: AddressLike,
    timestamp: BigNumberish,
    evidenceHash: BytesLike
  ];
  export type OutputTuple = [
    vendorId: bigint,
    rater: string,
    timestamp: bigint,
    evidenceHash: string
  ];
  export interface OutputObject {
    vendorId: bigint;
    rater: string;
    timestamp: bigint;
    evidenceHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VendorRegisteredEvent {
  export type InputTuple = [
    vendorId: BigNumberish,
    name: string,
    location: string
  ];
  export type OutputTuple = [vendorId: bigint, name: string, location: string];
  export interface OutputObject {
    vendorId: bigint;
    name: string;
    location: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface NightFairHygiene extends BaseContract {
  connect(runner?: ContractRunner | null): NightFairHygiene;
  waitForDeployment(): Promise<this>;

  interface: NightFairHygieneInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  COOLDOWN_PERIOD: TypedContractMethod<[], [bigint], "view">;

  addAuthority: TypedContractMethod<
    [authority: AddressLike],
    [void],
    "nonpayable"
  >;

  allowAuthorityAccess: TypedContractMethod<
    [vendorId: BigNumberish],
    [void],
    "nonpayable"
  >;

  confidentialProtocolId: TypedContractMethod<[], [bigint], "view">;

  getAllVendorIds: TypedContractMethod<[], [bigint[]], "view">;

  getVendorAggregatedScores: TypedContractMethod<
    [vendorId: BigNumberish],
    [
      [string, string, string, bigint] & {
        cleanliness: string;
        gloveWearing: string;
        wasteManagement: string;
        ratingCount: bigint;
      }
    ],
    "view"
  >;

  getVendorEvidenceHashes: TypedContractMethod<
    [vendorId: BigNumberish],
    [string[]],
    "view"
  >;

  getVendorInfo: TypedContractMethod<
    [vendorId: BigNumberish],
    [NightFairHygiene.VendorStructOutput],
    "view"
  >;

  getVendorRatingHistory: TypedContractMethod<
    [vendorId: BigNumberish],
    [NightFairHygiene.RatingStructOutput[]],
    "view"
  >;

  isAuthorizedAuthority: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  lastRatingTime: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  registerVendor: TypedContractMethod<
    [name: string, location: string],
    [bigint],
    "nonpayable"
  >;

  removeAuthority: TypedContractMethod<
    [authority: AddressLike],
    [void],
    "nonpayable"
  >;

  submitRating: TypedContractMethod<
    [
      vendorId: BigNumberish,
      inputCleanliness: BytesLike,
      inputGloveWearing: BytesLike,
      inputWasteManagement: BytesLike,
      inputProof: BytesLike,
      evidenceHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  vendorAggregatedCleanliness: TypedContractMethod<
    [arg0: BigNumberish],
    [string],
    "view"
  >;

  vendorAggregatedGloveWearing: TypedContractMethod<
    [arg0: BigNumberish],
    [string],
    "view"
  >;

  vendorAggregatedWasteManagement: TypedContractMethod<
    [arg0: BigNumberish],
    [string],
    "view"
  >;

  vendorCount: TypedContractMethod<[], [bigint], "view">;

  vendorIds: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  vendors: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, boolean, bigint] & {
        id: bigint;
        name: string;
        location: string;
        exists: boolean;
        ratingCount: bigint;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "COOLDOWN_PERIOD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "addAuthority"
  ): TypedContractMethod<[authority: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "allowAuthorityAccess"
  ): TypedContractMethod<[vendorId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "confidentialProtocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getAllVendorIds"
  ): TypedContractMethod<[], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getVendorAggregatedScores"
  ): TypedContractMethod<
    [vendorId: BigNumberish],
    [
      [string, string, string, bigint] & {
        cleanliness: string;
        gloveWearing: string;
        wasteManagement: string;
        ratingCount: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getVendorEvidenceHashes"
  ): TypedContractMethod<[vendorId: BigNumberish], [string[]], "view">;
  getFunction(
    nameOrSignature: "getVendorInfo"
  ): TypedContractMethod<
    [vendorId: BigNumberish],
    [NightFairHygiene.VendorStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getVendorRatingHistory"
  ): TypedContractMethod<
    [vendorId: BigNumberish],
    [NightFairHygiene.RatingStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "isAuthorizedAuthority"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "lastRatingTime"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registerVendor"
  ): TypedContractMethod<
    [name: string, location: string],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "removeAuthority"
  ): TypedContractMethod<[authority: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "submitRating"
  ): TypedContractMethod<
    [
      vendorId: BigNumberish,
      inputCleanliness: BytesLike,
      inputGloveWearing: BytesLike,
      inputWasteManagement: BytesLike,
      inputProof: BytesLike,
      evidenceHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "vendorAggregatedCleanliness"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "vendorAggregatedGloveWearing"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "vendorAggregatedWasteManagement"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "vendorCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "vendorIds"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "vendors"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, boolean, bigint] & {
        id: bigint;
        name: string;
        location: string;
        exists: boolean;
        ratingCount: bigint;
      }
    ],
    "view"
  >;

  getEvent(
    key: "AuthorityAdded"
  ): TypedContractEvent<
    AuthorityAddedEvent.InputTuple,
    AuthorityAddedEvent.OutputTuple,
    AuthorityAddedEvent.OutputObject
  >;
  getEvent(
    key: "AuthorityRemoved"
  ): TypedContractEvent<
    AuthorityRemovedEvent.InputTuple,
    AuthorityRemovedEvent.OutputTuple,
    AuthorityRemovedEvent.OutputObject
  >;
  getEvent(
    key: "RatingSubmitted"
  ): TypedContractEvent<
    RatingSubmittedEvent.InputTuple,
    RatingSubmittedEvent.OutputTuple,
    RatingSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "VendorRegistered"
  ): TypedContractEvent<
    VendorRegisteredEvent.InputTuple,
    VendorRegisteredEvent.OutputTuple,
    VendorRegisteredEvent.OutputObject
  >;

  filters: {
    "AuthorityAdded(address)": TypedContractEvent<
      AuthorityAddedEvent.InputTuple,
      AuthorityAddedEvent.OutputTuple,
      AuthorityAddedEvent.OutputObject
    >;
    AuthorityAdded: TypedContractEvent<
      AuthorityAddedEvent.InputTuple,
      AuthorityAddedEvent.OutputTuple,
      AuthorityAddedEvent.OutputObject
    >;

    "AuthorityRemoved(address)": TypedContractEvent<
      AuthorityRemovedEvent.InputTuple,
      AuthorityRemovedEvent.OutputTuple,
      AuthorityRemovedEvent.OutputObject
    >;
    AuthorityRemoved: TypedContractEvent<
      AuthorityRemovedEvent.InputTuple,
      AuthorityRemovedEvent.OutputTuple,
      AuthorityRemovedEvent.OutputObject
    >;

    "RatingSubmitted(uint256,address,uint256,bytes32)": TypedContractEvent<
      RatingSubmittedEvent.InputTuple,
      RatingSubmittedEvent.OutputTuple,
      RatingSubmittedEvent.OutputObject
    >;
    RatingSubmitted: TypedContractEvent<
      RatingSubmittedEvent.InputTuple,
      RatingSubmittedEvent.OutputTuple,
      RatingSubmittedEvent.OutputObject
    >;

    "VendorRegistered(uint256,string,string)": TypedContractEvent<
      VendorRegisteredEvent.InputTuple,
      VendorRegisteredEvent.OutputTuple,
      VendorRegisteredEvent.OutputObject
    >;
    VendorRegistered: TypedContractEvent<
      VendorRegisteredEvent.InputTuple,
      VendorRegisteredEvent.OutputTuple,
      VendorRegisteredEvent.OutputObject
    >;
  };
}
